### ISSUE TITLE
[Task] 3d 전시 데모 페이지 랜더링 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#102]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: 3d 전시 데모 페이지 랜더링 / 박지영

**TODO**
1. [x] 더미 데이터(이미지) 넣고 3d 전시 환경 구현하기
2. [ ] (스크롤 조절에다가 추가로) 키보드 작동으로 카메라 위치 조정하기
3. [ ] 전시 상세페이지에서 3d 데모 확인하는 인입 버튼 만들기

**Estimated time**
```3h```

**Labels**
- Estimated time: ```E: 3h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ```High```
