### ISSUE TITLE
[Task] 반응형 Navbar 구현하기 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#103]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: 모바일 및 스크롤 시 대응하는 Navbar 구현하기

**TODO**
1. [x] 스크롤 100 이상일 때 상단 navbar 고정시키기
2. [x] 스크롤 100 이상일 때 상단 navbar 색상 변경시키기
3. [x] 스크롤 100 이상일 때 상단 navbar height 작게 조절(로고 크기 및 위치 등)
4. [x] width 768px 이하 일 때 navbar의 모든 버튼들은 햄버거아이콘 안으로 숨기기

**Estimated time**
```6h```

**Labels**
- Estimated time: ```E: 6h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__1```
- Urgency: ```High```
