### ISSUE TITLE
[Task] 단일작품 컴포넌트 내 구매의사 알림 보내기 모달창 구현 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#105]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: 단일작품 컴포넌트 내 구매의사 알림 보내기 모달창 구현

**TODO**
1. [x] 작품 타이틀 옆에 옵션 버튼 추가
2. [x] 해당 버튼 클릭 시 작가에게 구매의사 알림 보내기 모달창 띄우기
3. [x] 기존 서브 카테고리 내 auction 메뉴는 삭제

**Estimated time**
```3h```

**Labels**
- Estimated time: ```E: 3h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__1```
- Urgency: `` Middle```
