### ISSUE TITLE
[Task] Gallery 목록 및 Gallery 상세페이지 레이아웃  / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#11]
**ISSUE**
- Group: ```client```
- Type: ```layout```
- Detail: 더미데이터 넣고 Gallery 목록 및 Gallery 상세페이지 레이아웃

**TODO**
1. [x] Gallery 목록 내 단일 컴포넌트 
2. [x] 9개 작품 슬라이더 
3. [x] 슬라이더 내 작품 전시 디자인
4. [x] 작품 클릭 시 단일 작품 페이지 

**Estimated time**
```8h```

**Labels**
- Estimated time: ```E: 8h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__1```
- Urgency: ```High```
