### ISSUE TITLE
[Task] 전시신청 POST 요청 및 응답 구현 / 박지영, 이동욱

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#121]
**ISSUE**
- Group: ```client```, ```server```
- Type: ```feature```
- Detail: gallery register POST 요청 및 응답 구현

**TODO**
1. [x] 클라이언트: 전시 신청 요청 axios POST 요청 구현
2. [x] 서버: DB에 레코드 생성 및 응답
3. [x] (에러 발생 시) 디버깅

**Estimated time**
```1h```

**Labels**
- Estimated time: ```E: 1h```
- Group : ```client```,``` server```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ```High```
