### ISSUE TITLE
[Task] Gallery 목록 불러오기 GET 요청 및 응답 구현 / 이동욱, 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#128]
**ISSUE**
- Group: ```client```, ```server```
- Type: ```feature```
- Detail: Gallery 목록 불러오기 GET 요청 및 응답 구현

**TODO**
1. [x] 클라이언트: 전시 신청 요청 axios GET 요청 구현
2. [x] 서버: DB에 레코드 생성 및 응답
3. [ ] (에러 발생 시) 디버깅

**Estimated time**
```1h```

**Labels**
- Estimated time: ```E: 1h```
- Group : ```client```,``` server```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ```High```
