### ISSUE TITLE
[Task] 전시회 찜하기 POST 요청 및 응답 구현 / 이동욱, 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#129]
**ISSUE**
- Group: ```client```, ```server```
- Type: ```feature```
- Detail: 전시회 찜하기 POST 요청 및 응답 구현

**TODO**
1. [x] 클라이언트: 찜하기/찜하기 해제 요청 axios POST/DELETE 요청 구현
2. [x] 서버: DB에 레코드 생성 및 응답
3. [x] (에러 발생 시) 디버깅
4. [x] 클라이언트: 찜하기 아이콘 랜더링 확인

**Estimated time**
```1h```

**Labels**
- Estimated time: ```E: 1h```
- Group : ```client```,``` server```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ```High```
