### ISSUE TITLE
[Task] 단일작품 상세 컴포넌트(모달창) 리팩토링 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#150]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: 단일작품 상세 컴포넌트(모달창) 리팩토링

**TODO**
1. [ ] 단일작품 확대 페이지를 라우팅으로 별도 분리된 페이지가 아니라 모달창으로 변경
2. [ ] 단일작품 제목/제작연도/재료/크기/상세설명을 이미지 옆에 overlay 시키기
3. [ ] Gallery 이미지 슬라이더에서 작품 클릭 시 단일작품 확대 페이지(—> 모달창)으로 이동 

**Estimated time**
```3h```

**Labels**
- Estimated time: ```E: 3h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ```High```
