### ISSUE TITLE
[Task] flow에 따른 반응형,레이아웃 수정 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#153]
**ISSUE**
- Group: ```client```
- Type: ```refactor```
- Detail: flow에 따른 반응형,레이아웃 수정 

**TODO**
1. [ ] 카카오맵 배포도메인 허용
2. [ ] 로고정하기
3. [ ] 관람객 로그인에만 오아쓰 넣는 형식으로 레이아웃 변경
4. [ ] 작가회원가입에서 이미지와 작가소개 삭제
5. [ ] 가입및로그인 부분 반응형 조정
6. [ ] 비밀번호 visibility 및 유효성검사

**Estimated time**

```4h```
