### ISSUE TITLE
[Task] mypage 리팩토링 및 더미데이터로 기능 구현시도 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#157]
**ISSUE**
- Group: ```client```
- Type: ```bug```, ```feature```
- Detail: mypage 리팩토리 및 기능구현

**TODO**
1. [ ] subnav, myinfo, mypick, mygallery 레이아웃 및 반응형 
2. [ ] modify s3이미지 버켓연결 / 이미지input생성하고 숨기기
3. [ ] modify 비밀번호 암호화
4. [ ] modify 유효성
5. [ ] modify 수정시 모달 

**Estimated time**

```8h```
