### ISSUE TITLE
[Task] admin페이지 getEx통신, 분기한페이지별로 데이터 렌더링 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#158]
**ISSUE**
- Group: ```client```
- Type: ```bug```, ```feature``````refactor```
- Detail: admin페이지 기능구현1 

**TODO**
1. [ ] admin 리팩토링(레이아웃, admin버튼)
2. [ ] admin getEx 통신 시도
3. [ ] admin 전시관리/리뷰관리 대분류 
4. [ ] admin 승인대기, 마감대기, 마감된전시 3가지로 분기하기 
5. [ ] admin분기한 페이지와  getEx 상태값(0,1,2) 각각 연결하여 렌더링 
6. [ ] admin 리팩토링(api통신시 무한루프 도는 문제 해결)
7. [ ] loadingIndicator 만들기
