### ISSUE TITLE
 [Task] navbar,회원가입,로그인  레이아웃 및 페이지 변경 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#18]
**ISSUE**
- Group: ```client```,
- Type: ```setting```
- Detail:회원가입,로그인  레이아웃 및 페이지 변경 

**TODO**
1. [x] 회원가입 , 회원가입디테일 페이지 
2. [x] 로그인, 로그인 디테일페이지
3. [x] 클릭한 유저에 따라 필요컴포넌트 보이기
4. [ ] navbar 레이아웃

**Estimated time**
> Pick one

```6h```
