### ISSUE TITLE
[Task] Review 목록 및 Review 상세페이지 레이아웃&디자인 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#22]
**ISSUE**
- Group: ```client```
- Type: ```layout```
- Detail: 더미데이터 넣고 Review 목록 및 Review 상세페이지 레이아웃&디자인

**TODO**
<어제 못한 것>
1. [ ] Gallery 목록에서 썸네일을 하위 컴포넌트로 연결했더니 maximum call stack 초과 에러가 계속 떴음. 시간을 일단 효율적으로 쓰기 위하여 하위 컴포넌트로 연결하지 않고, 상위 컴포넌트에 더미데이터를 나열함. 문제 원인을 파악해봐야 함.
2. [x] Gallery 목록에서 STANDARD/MEDIUM 상태값으로 조절 필요.
3. [x] Gallery 목록에서 별표(즐겨찾기) 아이콘 overlay 필요.
3. [x] Gallery 목록에서 정렬/필터 버튼들 추가해야 함.
4. [x] Gallery 상세페이지에서 상단에 카테고리 tags 나열 필요.
4. [ ] 이미지 카드 슬라이더 제작 완료. 다만 코드가 맘에 들지 않는다. 코드 리팩토링 필요.
5. [x] 이미지 카드 슬라이더 아래 9개 땡땡이 클릭 시 색상 변경 필요.
6. [x] 이미지 카드 슬라이더 좌/우 화살표 버튼 추가 제작하여 기능 개선 필요.
7. [ ] 단일작품 확대 페이지 반응형 레이아웃을 살짝 변경 필요.(ref 사이트 참고)
8. [ ] 단일작품 확대 페이지에서 작품 설명 어떻게 overlay 시킬지 고민해봐야 함.

<새로 해야 할 것>
1. [x] Review 목록 페이지 더미데이터 넣고 레이아웃 및 디자인 작업
2. [x] Review 상세 페이지 더미데이터 넣고 레이아웃 및 디자인 작업

**Estimated time**
```8h```

**Labels**
- Estimated time: ```E: 8h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__1```
- Urgency: ```High```
