### ISSUE TITLE
[Task] 모달창 분리된 컴포넌트로 리팩토링 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#253]
**ISSUE**
- Group: ```client```
- Type:  ```refactor```
- Detail: 페이지 내에 존재하는 모든 모달창은 단일 컴포넌트로 분리하기

**TODO**
1. [x] register 페이지 내 모달창 분리
2. [x] gallery 페이지 내 모달창 분리
3. [x] galleryDetail 페이지 내 모달창 분리
4. [x] reviewDetail 페이지 내 모달창 분리
5. [x] 3D페이지 내 모달창 분리

**Estimated time**
```1h```

**Labels**
- Estimated time: ```E: 1h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__3```
- Urgency: ``` Middle```
