### ISSUE TITLE
[Task] admin getAllReviews 함수 리팩토링 /문순려

### ISSUE THREAD

**Issue by Sunryeo** [codestates/art-ground#260]
**ISSUE**
- Group:  ```server```
- Type: ```refactor```
- Detail: 

**TODO**
1. [x] admin getAllReviews 함수 Sequelize 메소드 옵션 사용해서 리팩토링
2. [x] 작가 nickname 추가
3. [x] 응답 확인 및 디버깅

**Estimated time**
> Pick one

```1.5h```

**Labels**
- Estimated time: ```E: 1.5h```
- Group : ``` server```
- Sprint: ```Sprint__3__```
- Urgency: ```High```
