### ISSUE TITLE
[Task] admin-승인대기 리스트 - 신청 정보 디테일페이지 생성 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#266]
**ISSUE**
- Group: ```client```
- Type: ```bug```, ```feature```, ``layout```
- Detail: admin-승인대기시 신청 디테일페이지 생성

**TODO**
1. [x] 승인대기 목록에서 [자세히 보기] 클릭시 해당 작품신청 정보 확인할 수 있는 디테일 페이지 레이아웃
2. [x] 클릭한 해당 전시회 내역 불러와서 화면 렌더링 
3. [x] 다른 탭 클릭시 디테일 페이지 보이지 않도록 조절
4. [x] 뒤로가기 탭 만들어서 승인대기 목록으로 이동시키기 
5. [x] 반응형 조정 
6. [x] 텍스트 길게 들어가는 경우 글씨 밀리지 않도록 조정
7. [x] 이미지가 null인경우 noimage로 렌더
8. [x] 원본 이미지 크기 맞춰서 비율 들어가도록 렌더
9. [x] status -> 스탠다드/프리미엄 으로 렌더 
**Estimated time**
> Pick one
```4h```
