### ISSUE TITLE
[Task] 전시신청페이지 레이아웃 및 디자인 작업 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#27]
**ISSUE**
- Group: ```client```
- Type: ```layout```
- Detail: 전시신청페이지 레이아웃 및 디자인 작업

**TODO**
<어제 못한 것>
1. [x] Gallery 목록에서 썸네일을 하위 컴포넌트로 연결했더니 maximum call stack 초과 에러가 계속 떴음. 시간을 일단 효율적으로 쓰기 위하여 하위 컴포넌트로 연결하지 않고, 상위 컴포넌트에 더미데이터를 나열함. 문제 원인을 파악해봐야 함. —> 이거 도대체 왜 이러는지 정말 모르겠음!!!
2. [ ] 이미지 카드 슬라이더 제작 완료. 다만 코드가 맘에 들지 않는다. 코드 리팩토링 필요.
3. [x] 이미지 카드 슬라이더 좌/우 화살표 버튼 추가 제작하여 기능 개선 필요.
4. [x] 단일작품 확대 페이지 반응형 레이아웃을 살짝 변경 필요.(ref 사이트 참고)
5. [ ] 단일작품 확대 페이지에서 작품 설명 어떻게 overlay 시킬지 고민해봐야 함.
6. [x] Gallery 목록 & Review 목록 페이지에서 썸네일 height auto로 하면 안 됌. 수정 필요.
7. [x] 리뷰 상세페이지에 총 N개의 리뷰가 있어요 메세지 띄우기
8. [x] 해시태그 카테고리 컨텐츠 조율(팀원들과)

<새로 해야 할 것>
1. [ ] 위 목록 한개씩 해결(작업 완료하지 못한 것들)
2. [x] 전시신청페이지 레이아웃 및 디자인 작업
3. [x] 경매 페이지 레이아웃 및 디자인 작업
4. [ ] contact 페이지 레이아웃 및 디자인 작업
5. [x] about 페이지 레이아웃 및 디자인 논의하기(w/ 다희님)

**Estimated time**
```8h```

**Labels**
- Estimated time: ```E: 8h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__1```
- Urgency: ```High```
