### ISSUE TITLE
[Task] 배포환경에서 카카오 로그인 기능 테스트 / 문순려

### ISSUE THREAD

**Issue by Sunryeo** [codestates/art-ground#276]
**ISSUE**
- Group: ```server```
- Type: ```bug```, ```refactor```
- Detail: 

**TODO**
1. [x] 배포환경에서 카카오 로그인 기능 테스트
2. [x] 응답 확인 및 디버깅
3. [x] 카카오 동의 화면에 앱 로고 삽입하기

**Estimated time**
> Pick one

```1.5h```

**Labels**
- Estimated time: ```E: 1.5h```
- Group : ``` server```
- Sprint: ```Sprint__3__```
- Urgency: ```High```
