### ISSUE TITLE
[Task] admin페이지-전시관리,리뷰관리 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#278]
**ISSUE**
- Group: ```client```
- Type: ```bug```, ```feature```, ```refactor```
- Detail: admin페이지 전반

**TODO**
1. [x] (전시관리) get요청으로 전시 정보 전체 받아서 각각 승인대기, 마감대기, 마감된전시회로 분기하여 렌더
2. [x] (전시관리) 분기 페이지별 하위컴포넌트 생성해서 하위컴포넌트 렌더 
3. [x] (전시관리) 하위컴포넌트에서 get요청 받을시 mapping하면 무한루프뜨는 에러해결하기... -> 컴포넌트 뜯어고치기
2. [x] (전시관리) 각각 분기 탭을 클릭했을때, 클릭한 버튼에만 모양 및 색 변화주기
2. [x] (전시관리)이미지 등 배열형태의 요소 불러오기 에[러 => 조건문으로 조절하여 렌더 
3. [x] (전시관리) 분기할때마다 프롭스 데이터 늦게 받아오는 에러 해결
4. [x] (전시관리) 승인대기 리스트에는 <상세정보>볼 수 있는 클릭이벤트 생성해서 하위컴포넌트 가져와야함
5. [x] (전시관리) 승인대기시에는 '승인하기', 마감대기시에는 '마감하기' 클릭이벤트가 렌더되어야 함 
6. [x] (리뷰관리) 받아온 데이터중, 필요한 정보만 렌더시키기(타이틀,작가,리뷰작성자,댓글내용) 
7. [x] (리뷰관리) 리뷰관리 페이지가 렌더되는 경우에는 삭제하기 이벤트 버튼이 렌더되어야함.
8. [x] 관리자 아이디로 로그인 했을시에만 nav바에 '관리자페이지' 로 이동할 수 있는 버튼 나타나도록 해야함
9. [x] 반응형 조절
10. [x] (전시관리) 수정하기, 마감하기 버튼 클릭시 수정된 데이터값 변화해서 렌더되어야 함 .. -> 일단 뜨긴하지만, 수정해야함
