### ISSUE TITLE
[Task] 모달 추가 및  상태별 하위컴포넌트 렌더 여부 조정(useType,exhibition status) / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#280]
**ISSUE**
- Group: ```client```, 
- Type: ```bug```, ```feature```,```refactor```
- Detail: 모달 추가 및  상태별 하위컴포넌트 렌더 여부 조정

**TODO**
1. [x] admin 모달 추가 (승인체킹, 마감체킹) modals/confirmModal 하나 생성 -> 각각 상태별  txt상태 만들어서 상태별로 해당 txt띄우기  
2. [x] 로그인 유저 아닌경우 nav바  마이페이지 클릭시 모달뜨도록 -> 로그인페이지 이동 or 모달닫기 버튼 
3. [x] modify모달 추가 
4. [x] 마이페이지 sidebar 메뉴 작가인경우에 '내 전시회', '작가정보 텍스트란 ' 렌더해야함 -> 작가아닌경우 렌더되면 안됨.
