### ISSUE TITLE
[Task] mypage전반 ( 인포, 찜하기, 내전시회 ) / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#281]
**ISSUE**
- Group: ```client```
- Type: ```bug```, ```feature``` ```refactor```
- Detail: mypage전반

**TODO**

1. [x] (mypick) 1차 api통신 완료 및 렌더링 완료 
2. [x] (mypick) 이미지 데이터 추가적으로 받아서 렌더시켜야함 
3. [x] (myex) 1차 api통신 완료 및 렌더링 완료 (배열 형식 이미지 렌더 조건문으로 걸러줘야함)
4. [x] (myex) 승인대기 상태의 전시회의 경우 -> 나타낼 수 있는 표시해주기 
5. [x] 받아온 이미지 사이즈 다를경우 한쪽으로 밀리는 문제 수정하기
6. [x] 렌더할 데이터가 없는 경우 한쪽 컴포넌트에서만 에러 뜨고 렌더링 안되는 문제 해결하기 
7. [x] 6번문제 해결 후 null 데이터인 경우에는 없는이미지입니다 이미지 띄우기
