### ISSUE TITLE
[Task] about페이지 전반 / 유다희

### ISSUE THREAD

**Issue by tkdkagody** [codestates/art-ground#283]
**ISSUE**
- Group: ```client```
- Type: ```bug```, ```feature```, ```refactor```
- Detail: about페이지 전반

**TODO**
1. [x] about페이지 레이아웃 
2. [x] brand 설명란에 타이핑 효과 글자 js로 적용시키기
3. [x] aos 라이브러리 적용시키기 
4. [x] about페이지 스크롤내릴시 위치 이동 tab 컴포넌트 만들고 띄우기 (화면 fix)
5. [x] 섹션2에 이미지4개 짜리 슬라이더 만들고 4초마다 자동 이동시키기 
6. [x] 슬라이더에 커서 올리면 양쪽 이동버튼 나타나고 이동가능하게 하기
7. [x] 관람, 리뷰, 대관 설명 각각 대표 title이랑 설명 문구 
8. [ ] 관람 detail 섹션에 일단 관람종류 일단 이미지로 넣어두기(레이아웃 고민) -> 더미 추가 후 움짤로 변경 
9. [x] 리뷰 detail 섹션에 리뷰카드 올리기 => 카드 슬라이더 형식으로 수정 
10. [x] 움직이는 화살표 
11. [x] 둥둥 떠다니는 최하단 갤러리 둘러보기 
12. [x]  이용자 수 섹션으로  스크롤 이동시 숫자 카운터 올라가도록 하기 
13. [ ] 리액트슬릭 시도 -> 삽질만하고 css충돌로 기존 기능 작동안함..  (다시 시도)
14. [ ] 반응형 수정
