### ISSUE TITLE
[Task] redis  getExhibition / 이동욱

### ISSUE THREAD

**Issue by dongukuklee** [codestates/art-ground#293]
**ISSUE**
- Group:  ```server```
- Type:  ```refactor```
- Detail: 전시회 불러오기 캐싱

**TODO**
1. [x] 전체 데이터 받아오기
2. [x] standard 데이터 받아오기
3. [x] premium 데이터 받아오기

**Estimated time**

```2h```

**Labels**
- Estimated time: ```E: 2h```
- Group : ``` server```
- Urgency: ``` Middle```
