### ISSUE TITLE
[Task] 모바일 버전 버그 더블체크 후 코드수정 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#320]
**ISSUE**
- Group: ```client```
- Type: ```bug```
- Detail: 모바일 버전 버그 더블체크 후 코드수정

**TODO**
- [x]  이미지 슬라이더 터치 드래그 이벤트 작동 안 함.
- [x]  랜딩페이지 상단에 검정색 박스 보임.(사파리 브라우저에서) 
- [x]  위로 스크롤 할 때, 상단 도달 시 네비게이션 바가 사라졌다가 다시 내려옴(깜빡거리는 것 처럼 보임): 
- [x]  페이지 전환 시 스크롤이 상단에 있음에도 네비게이션 바가 안 보이는 경우도 있음.(매번 발생하는 에러는 아니라 일단 지켜볼 예정)
- [x]  갤러리 & 리뷰 목록에서 썸네일 두번 터치해야 상세페이지로 이동함. 
- [x]  글꼴이 브라우저마다 달라보이는 현상

**Estimated time**
```6h```

**Labels**
- Estimated time: ```E: 6h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__3```
- Urgency: ```High```
