### ISSUE TITLE
[Task] 갤러리 상세 & 리뷰 상세 페이지 인입 서브라우팅으로 수정하기 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#339]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: 갤러리 상세 & 리뷰 상세 페이지 인입 서브라우팅으로 수정하기

**TODO**
- [x]  갤러리 상세 & 리뷰 상세페이지: exhibition id를 기준으로 서브라우팅 적용하기.([https://velopert.com/2937](https://velopert.com/2937), [https://www.daleseo.com/react-router-nested/](https://www.daleseo.com/react-router-nested/))
- [x]  갤러리 상세 페이지 내에서 useEffect 호출하면 axios GET요청. 응답형태는 전체 갤러리목록에서 받았던 [{}, {}, {} ... ]—> 배열의 1개 요소와 동일. --> 응답데이터 랜더링하기
- [x]  리뷰 상세 페이지 내에서 useEffect 호출하면 axios GET요청. 응답형태는 `res.status(200).json({ exhibitionData , commentsData})` . 기존 댓글목록 받아오는 것 그대로 유지하고 exhibition 데이터(`exhibition.images[0].image_urls, exhibition.title, exhibition.author.nickname, exhibition.start_date & end_date, exhibition.genre_hashtags`)만 추가. --> 응답데이터 랜더링하기

**Estimated time**
```5h```

**Labels**
- Estimated time: ```E: 5h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__3```
- Urgency: ```High```
