### ISSUE TITLE
[Task] Gallery & Review 페이지 내 API 요청 코드 스키마 작성 / 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#52]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: Gallery & Review 페이지 내 API 요청 코드 스키마 작성

**TODO**
1. [x] Gallery 페이지 내 API request 리스트업
2. [x] Gallery 페이지 내 API request 코드 스키마
3. [x] Review 페이지 내 API request 리스트업
4. [x] Review 페이지 내 API request 코드 스키마

**Estimated time**
```3h```

**Labels**
- Estimated time: ```E: 3h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ``` Middle```
