### ISSUE TITLE
[Task] three.js 랜더링 시뮬레이션/ 박지영

### ISSUE THREAD

**Issue by devLuenna** [codestates/art-ground#53]
**ISSUE**
- Group: ```client```
- Type: ```feature```
- Detail: three.js 랜더링 시뮬레이션

**TODO**
1. [x] three.js 기본 개념 공부하기
2. [x] 사물 1개 랜더링(ex. 직육면체) 시뮬레이션 해보기
3. [x] 직육면체에 이미지 한개 붙여서 시뮬레이션 해보기

**Estimated time**
```6h```

**Labels**
- Estimated time: ```E: 6h```
- Group : ```client```
- Sprint: ```Sprint__NUMBER__2```
- Urgency: ``` Low```
