### ISSUE TITLE
[Task] 토큰 생성 함수 수정 및 쿠키 테스트 / 문순려

### ISSUE THREAD

**Issue by Sunryeo** [codestates/art-ground#57]
**ISSUE**
- Group: ```server```
- Type: ```bug```, ```feature```
- Detail: 

**TODO**
1. [ ] req.header.cookie로 토큰 생성 함수 수정
2. [ ] sendToken 함수 추가
3. [ ] 헤더에 쿠키 잘 들어오는 지 테스트

**Estimated time**
> Pick one

```2h```

**Labels**
- Estimated time: ```E: 2h```
- Group : ``` server```
- Sprint: ```Sprint__2__```
- Urgency: ```High```
